export const descricoesEnergias = {
    solar: "Energia solar é a energia que vem da luz e do calor do sol. Sendo uma fonte alternativa, renovável e sustentável de energia que provém da radiação eletromagnética (luz e calor) emanada diariamente pelo sol. Essa energia pode ser utilizada por diferentes tecnologias, como aquecedores solares, painéis fotovoltaicos e usinas heliotérmicas (ou termossolares).\n\nHoje em dia, o conceito de energia solar é comumente associado à geração limpa de eletricidade pelos painéis de energia fotovoltaica (painéis fotovoltaicos), que transformam a luz do Sol diretamente em energia elétrica.",

    eolica: "Energia eólica é um tipo de energia cinética causada pelo fluxo ou movimento do ar, frequentemente convertida em eletricidade por meio de turbinas eólicas, que capturam o movimento do vento e o transformam em energia elétrica.\n\nA tecnologia produz energia limpa, que permite reduzir as emissões de gases poluentes da queima de combustíveis fósseis, e hoje lidera a expansão das fontes de energia renováveis na geração elétrica mundial com a energia fotovoltaica.",

    hidrogenio: "A energia do hidrogênio é uma fonte limpa e sustentável que está se destacando como uma alternativa aos combustíveis fósseis. O hidrogênio é o elemento químico mais abundante no universo e pode ser usado como um vetor de energia, sendo uma substância capaz de armazenar e transportar energia.\n\nDessa forma, ao ser utilizada como combustível, o hidrogênio produz apenas água como subproduto, tornando-se uma opção eficaz para reduzir as emissões de gases de efeito estufa e combater as mudanças climáticas.\n\nO hidrogênio pode ser utilizado em células a combustível para gerar eletricidade, em motores de combustão interna adaptados e em processos industriais.",

    biomassa: "Biomassa é um material orgânico utilizado como fonte de energia renovável. Sua principal origem é vegetal, podendo ser obtida de diversas fontes, como resíduos agrícolas, florestais, urbanos e industriais.\n\nTrata-se de uma fonte de Energia renovável, uma vez que a sua decomposição libera gás carbônico na atmosfera, o qual, ao longo do seu ciclo, é transformado em hidrato de carbono por meio da fotossíntese realizada pelas plantas. Portanto, a geração de energia de biomassa é uma opção viável para substituir combustíveis fósseis e poluentes.\n\nA biomassa é produzida a partir de substâncias de origem orgânica, sejam de origem vegetal ou animal, tais como resíduos agrícolas, excrementos de animais, resíduos florestais e bagaço de cana-de-açúcar.",

    geotermica: "A energia geotérmica é uma fonte renovável que aproveita o calor proveniente do interior da Terra.\n\nEssa energia vem do calor proveniente do interior da Terra, que é composta por diversas camadas. Na camada superior, encontra-se a crosta terrestre, uma estrutura fina composta por rochas. Logo abaixo está o manto terrestre, uma camada profunda formada por magma, uma mistura de rochas em estado líquido e pastoso devido às elevadas temperaturas no interior do planeta.\n\nÉ comum que todo esse calor se manifeste em determinadas áreas da superfície terrestre, em razão de fendas geológicas e erupções vulcânicas. Tudo isso provoca o surgimento de gêiseres de vapor e nascentes de água quente. Nesse momento, é possível a obtenção da energia geotérmica.",

    hidreletrica: "A energia hidrelétrica é uma fonte de energia renovável que utiliza o fluxo natural da água em movimento para gerar eletricidade. Esse processo acontece nas instalações de usinas hidrelétricas, que possuem capacidade de captar e transformar essa força em energia.\n\nEssa energia funciona por meio da transformação de energia cinética em eletricidade. As barragens contêm grandes quantidades de água provenientes de rios.\n\nAo passar pelos tubos das barragens, a força da água, que cai com a ajuda da gravidade, movimenta as turbinas. Essas turbinas estão acopladas a geradores responsáveis pela geração da energia elétrica.\n\nGeradas pela força das águas e pela luz do sol, a energia hidrelétrica e a energia solar são duas fontes limpas e renováveis para a geração de eletricidade.",

    maremotriz: "Tecnologia para converter a energia das marés em formas úteis de energia, sendo uma energia renovável que aproveita as variações de nível das marés para gerar eletricidade. Essa forma de energia é obtida através da captura da energia cinética associada ao movimento das massas de água resultante do fluxo e refluxo das marés.\n\nEla é considerada uma fonte de energia limpa e sustentável, pois é gerada a partir de uma fonte natural e renovável – as marés, que são influenciadas principalmente pela atração gravitacional da lua e do Sol sobre a Terra. No entanto, a viabilidade econômica e ambiental dos projetos pode depender das características específicas do local escolhido para a instalação."
}
